#!/bin/bash

LOG=~/smplay_start_service_wrapper.log
{
  echo $@
  pwd
  echo "=========== Original file ============="
  cat $1
  echo "=========== Modified file ============="
  cat $1 | awk '{
    # only for lines with Duser.dir
    if( /Duser.dir/ ) {
       # find the first =
       split($0, a, "=")
       # check if the line ends with "
       if( /\"$/ ) {
         sub(/\"$/,"",a[2])
         print sprintf("%s=$(cygpath -d %s)\"",a[1],a[2])
       } else {
         print sprintf("%s=$(cygpath -d %s)",a[1],a[2])
       }
    } else print $0

  }' > ${1}.new
  cat ${1}.new

  mv ${1}.new  ${1}
  chmod +x ${1}
} > $LOG


exec "$@"
